version: '3.7'

services:
  portainer:
    image: portainer/portainer:1.22.0
    container_name: Portainer
    restart: always
    networks:
      - local
    hostname: unix:///var/run/docker.sock
    ports:
      - 50443:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  local:
    driver: bridge